# Generated by Django 4.1.3 on 2022-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
                ('calorias', models.CharField(max_length=150)),
                ('fecha_vencimiento', models.CharField(max_length=150)),
            ],
        ),
    ]
